jobs:
- name: hello-world
  plan:
  - get: pipeline-repo
    trigger: true
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]

resources:
- name: pipeline-repo
  type: git
  source:
    uri: git@github.com:heycait/pipeline-code.git
    branch: master

